FROM codercom/code-server:4.96.4
USER root
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    # Python
    && apt-get install -y python3 python3-pip python3-venv \
    # Java
    && apt-get install -y openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER coder
EXPOSE 8080
RUN mkdir -p /tmp/kanvas
CMD ["code-server","--auth","none","--bind-addr","0.0.0.0:8080","/tmp/kanvas"]