FROM node:20-bullseye-slim AS builder
# FROM node:20.20.0-bullseye-slim

# # Install required system libraries for onnxruntime
# RUN apt-get update && apt-get install -y \
#     libgomp1 \
#     libc6 \
#     && rm -rf /var/lib/apt/lists/*
WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN ls
COPY ./package*.json ./
RUN ls
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN npm run prebuild

FROM node:20-bullseye-slim AS production

RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
COPY package*.json ./
# RUN npm install 
COPY --from=builder /app/node_modules ./node_modules  
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/generated ./src/generated
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY prisma ./prisma    
# taking prisma from source code
EXPOSE 9092
CMD ["node","dist/index.js"]