FROM node:20.20.0-bullseye-slim

# Install required system libraries for onnxruntime
RUN apt-get update && apt-get install -y \
    libgomp1 \
    libc6 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

ARG DATABASE_URL

ENV DATABASE_URL=$DATABASE_URL

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN npm run prebuild
EXPOSE 9092
CMD ["npm","run","start"]