FROM node:20.20.0-alpine AS builder
WORKDIR /app
RUN apk add --no-cache zip unzip

COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build  

FROM node:20 AS production
WORKDIR /app
ARG AUTO_SCALING_GROUP_NAME
ARG ACC_KEY_ID
ARG SECRET_ACC_KEY
ARG BUCKET_NAME
ARG PORT=9095
ENV AUTO_SCALING_GROUP_NAME=$AUTO_SCALING_GROUP_NAME
ENV ACC_KEY_ID=$ACC_KEY_ID
ENV PORT=$PORT
ENV SECRET_ACC_KEY=$SECRET_ACC_KEY
ENV BUCKET_NAME=$BUCKET_NAME
COPY ./package*.json ./
RUN npm install
COPY --from=builder /app/dist ./dist
EXPOSE 9095
CMD ["node","dist/index.js"]