FROM node:20.20.0-bullseye-slim

# Install required system libraries for onnxruntime
RUN apt-get update && apt-get install -y \
    libgomp1 \
    libc6 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm","run","dev"]
