FROM node:20-alpine AS builder
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GOOGLE_SECRET
ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_SECRET=$VITE_GOOGLE_SECRET
# FROM node:20.20.0-bullseye-slim

# Install required system libraries for onnxruntime
# RUN apt-get update && apt-get install -y \
#     libgomp1 \
#     libc6 \
#     && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS production
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf  
EXPOSE 5174
CMD ["nginx","-g","daemon off;"]
